name: Build ImmortalWrt (master)

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable SSH for menuconfig'
        required: false
        default: 'false'


env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master

  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config

  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh

  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true

  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize build environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/*
        sudo apt-get update -y
        sudo apt-get install -y $(curl -fsSL https://raw.githubusercontent.com/P3TERX/Actions-OpenWrt/main/general/ubuntu2204)
        sudo timedatectl set-timezone "$TZ"

    - name: Clone ImmortalWrt source
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: Load custom feeds
      run: |
        [ -f "$FEEDS_CONF" ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        ../$DIY_P1_SH

    - name: Update & install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom config
      run: |
        [ -f "$CONFIG_FILE" ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        ../$DIY_P2_SH

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: github.event.inputs.ssh == 'true'


    - name: Make defconfig
      run: |
        cd openwrt
        make defconfig

    - name: Download packages
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -delete

    - name: Compile firmware
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      if: success() && env.UPLOAD_FIRMWARE == 'true'
      with:
        name: ImmortalWrt-master-firmware
        path: openwrt/bin/targets
